// components/SyntheticDataTable.js
import React from 'react';
import { Table } from 'react-bootstrap';

// Displays a table of synthetic data entries generated by AI
const SyntheticDataTable = ({ data }) => {
  if (!data || data.length === 0) {
    return <div className="text-muted">No synthetic data generated.</div>;
  }

  // Derive table columns from first entry
  const columns = Object.keys(data[0] || {});

  return (
    <div className="table-responsive">
      <Table striped bordered hover size="sm">
        <thead>
          <tr>
            {columns.map(col => (
              <th key={col}>{col.replace(/([A-Z])/g, ' $1')}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, idx) => (
            <tr key={idx}>
              {columns.map(col => (
                <td key={col}>{row[col]}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </Table>
    </div>
  );
};

export default SyntheticDataTable;
