// components/SyntheticDataTable.js
import React from 'react';
import { Table } from 'react-bootstrap';

/**
 * Render table of synthetic data generated by the AI backend
 * @param {Object[]} data Array of synthetic data objects
 */
const SyntheticDataTable = ({ data }) => {
  // If no data is provided or the data array is empty, you should display a message to the user indicating that no synthetic data has been generated.
  // Example: Return a <div> element with a suitable class name and message.

  // If there is data, extract the column names.
  // Use Object.keys on the first object in the 'data' array to define the 'columns' variable.
  // Example: const columns = Object.keys(data[0]);
  
  // Render a responsive table using the Table component from react-bootstrap:
  // 1. Create the table header: 
  //    - For each column name in 'columns', render a <th> element.
  //    - Optionally, format the column names (e.g., insert spaces before capital letters using a RegExp) for display purposes.
  // 2. Create the table body:
  //    - For each row in the 'data' array, render a <tr>.
  //    - For each column, render a <td> that displays the corresponding value in the current row using the column key.

  // Ensure to wrap the table in a responsive container (e.g., <div className="table-responsive">) for better styling and overflow handling.

  // Example structure:
  // return (
  //   <div className="table-responsive">
  //     <Table ...>
  //       <thead>...</thead>
  //       <tbody>...</tbody>
  //     </Table>
  //   </div>
  // );
};

export default SyntheticDataTable;