// components/SyntheticDataTable.js
import React from 'react';
import { Table } from 'react-bootstrap';

// Displays a table of synthetic data entries generated by AI
const SyntheticDataTable = ({ data }) => {
  // If no data is provided or the data array is empty
  // Instruction: Check whether the 'data' prop exists and has at least one item.
  // If not, display a div with a message (class 'text-muted') saying 'No synthetic data generated.'

  // Derive table columns from first entry
  // Instruction: Identify the column headers for the table by extracting keys from the first object in 'data'.
  // Store these column names in a variable called 'columns'.

  // Instruction: Return a responsive table layout using react-bootstrap components.
  // 1. Render a Table component with the following properties: striped, bordered, hover, and size="sm".
  // 2. Create the table header (<thead>) with a single row (<tr>):
  //      - For each column name in 'columns', render a <th> and format the column name by adding a space before capital letters (e.g., 'FirstName' -> 'First Name').
  // 3. Create the table body (<tbody>):
  //      - For each 'row' in 'data', render a new table row (<tr>).
  //      - For each column, display the corresponding value from the row inside a <td>.
  //      - Use 'idx' (index of the row) as the key for the row, and column name as the key for <td>.
  // Ensure proper key usage for React rendering efficiency.
};

export default SyntheticDataTable;
